# Knight's Walk

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### Part 1 - Initialize the board


https://www.youtube.com/watch?v=RGQe8waGJ4w (runtime: 6:12)

We will store the chess board in a 2d- numpy array of integers. The size of the board is $(2n+1)$-by-$(2n+1)$, for a given integer $n$. This means the board extends from the center square by $n$ steps in all directions.

The first step is to initialize the board by filling it with the integers described in the video. Finish the implementation of the function definition in the cell below such that it returns this "spiral pattern" for any given input parameter $n$.

An example is given below: for the following input
```python
board = initialize_board(3)
```
the correct output is
```julia
7×7 Array{Int64,2}:
 37  36  35  34  33  32  31
 38  17  16  15  14  13  30
 39  18   5   4   3  12  29
 40  19   6   1   2  11  28
 41  20   7   8   9  10  27
 42  21  22  23  24  25  26
 43  44  45  46  47  48  49
```

Test your function for various values of $n$ to make sure it is correct before you continue.

*Hints*:
- Note that since Python uses 0-based indexing, the center square of the array `board` is given by element `board[n,n]`.
- After the center $1$ has been placed, there are exactly $n$ "circles" of numbers of increasing radius. This is naturally implemented using a for-loop.
- In each "circle", there are 4 segments going up, left, down, and right. These are also naturally implemented using a sequence of 4 for-loops.

In [6]:
def initialize_board(n):
    dim_board = 2*n + 1
    board = np.zeros((dim_board, dim_board), dtype=int)

    # Set the center of the board as the starting position
    center = n
    board[center, center] = 1

    # Set the rest of the board in increasing order from the center
    value = 2
    for circle in range(1, n+1):
        for up in range(n+circle,n-circle,-1): #right segment
            board[up-1, n+circle] = value
            value+=1

        for left in range(n+circle,n-circle,-1): #top segment
            board[n-circle, left-1] = value
            value+=1

        for down in range(n-circle,n+circle): #left segment
            board[down+1, n-circle] = value
            value+=1

        for right in range(n-circle,n+circle): #bottom segment
            board[n+circle,right+1] = value
            value+=1

    return board

In [7]:
# Use the initialize_board function to create a board
initialize_board(2)

array([[17, 16, 15, 14, 13],
       [18,  5,  4,  3, 12],
       [19,  6,  1,  2, 11],
       [20,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

In [17]:
def initialize_board_alt(n):
    dim_board = 2*n + 1
    board = np.zeros((dim_board, dim_board), dtype=int)

    # Set the center of the board as the starting position
    x, y = n, n
    board[x, y] = 1

    value = 2

    for circle in range(n):
        x+=1
        y+=1
        steps = 2*(circle+1)
        for _ in range(steps):
            x -= 1
            board[x, y] = value
            value += 1

        for _ in range(steps):
            y -= 1
            board[x, y] = value
            value += 1

        for _ in range(steps):
            x += 1
            board[x, y] = value
            value += 1

        for _ in range(steps):
            y += 1
            board[x, y] = value
            value += 1

    return board

In [18]:
initialize_board_alt(2)

array([[17, 16, 15, 14, 13],
       [18,  5,  4,  3, 12],
       [19,  6,  1,  2, 11],
       [20,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

### Part 2 - Simulate the walk


Next we will write the function to simulate the walk and produce the sequence. This function will take an initialized board as input, and produce a list of numbers as well as the corresponding x- and y-coordinates.

For example, the following input:
```julia
board = initialize_board(2)
display(board)
seq, xs, ys = simulate_walk(board);
print("Sequence = ", seq)
print("x-coordinates = ", xs)
print("y-coordinates = ", ys)
```
should produce the following correct output:
```julia
5×5 Array{Int64,2}:
 17  16  15  14  13
 18   5   4   3  12
 19   6   1   2  11
 20   7   8   9  10
 21  22  23  24  25
Sequence = [1, 10, 3, 6, 9, 4, 7, 2, 5, 8, 11, 14]
x-coordinates = [0, 2, 1, -1, 1, 0, -1, 1, -1, 0, 2, 1]
y-coordinates = [0, 1, -1, 0, 1, -1, 1, 0, -1, 1, 0, -2]
```

Again test your code, first using small values of $n$ as shown above, which makes it easier to look at the results and find errors.

*Hints*:
- It is convenient to create another 2d-array of booleans, indicating if a square has been visited or not.
- Make sure you never allow the knight to jump outside the board. That is, the only valid positions are $n$ steps from the center square in either direction

In [ ]:
def simulate_walk(board):
    sequence = []; x_coordinates = []; y_coordinates = []       
    # Simulate the knight's walk on the board
    
    
    return(sequence,x_coordinates,y_coordinates)

In [ ]:
board = initialize_board(2)
display(board)
sequence,x_coordinates,y_coordinates = simulate_walk(board)
print("Sequence = ", sequence)
print("x-coordinates = ", x_coordinates)
print("y-coordinates = ", y_coordinates)

In [ ]:
n = 100
board = initialize_board(n)
sequence,x_coordinates,y_coordinates = simulate_walk(board)
print("last element = ", int(sequence[-1]))
print(f"with coordinates ({x_coordinates[-1]},{y_coordinates[-1]})")
# y_coordinates = np.negative(y_coordinates)
plt.plot(x_coordinates, y_coordinates)
plt.annotate('X',xy=(x_coordinates[-1],y_coordinates[-1]), color='red', size=20)
plt.grid()